from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional
from services.github import parse_pr_url, post_pr_comment, post_pr_review_comment

router = APIRouter()


class CommentRequest(BaseModel):
    url: str
    feedback: dict
    github_token: Optional[str] = None


class CommentResponse(BaseModel):
    success: bool
    comment_url: str
    message: str


def format_feedback_as_markdown(feedback: dict, pr_url: str) -> str:
    """Format the AI feedback dict into a nicely formatted GitHub comment."""
    health_score = feedback.get("health_score", 0)
    language = feedback.get("language", "Unknown")
    summary = feedback.get("summary", "No summary.")
    issues = feedback.get("issues", [])

    # Health score emoji
    if health_score >= 71:
        score_emoji = "🟢"
        score_label = "Healthy"
    elif health_score >= 41:
        score_emoji = "🟡"
        score_label = "Needs Attention"
    else:
        score_emoji = "🔴"
        score_label = "Critical Issues"

    bugs = [i for i in issues if i.get("severity") == "bug"]
    warnings = [i for i in issues if i.get("severity") == "warning"]
    suggestions = [i for i in issues if i.get("severity") == "suggestion"]

    lines = [
        "## 🤖 AI Code Review",
        "",
        f"> Powered by DeepSeek AI | Language: **{language}**",
        "",
        f"### {score_emoji} Health Score: {health_score}/100 — {score_label}",
        "",
        "### 📋 Summary",
        "",
        summary,
        "",
    ]

    if issues:
        lines += [
            "### 🔍 Issues Found",
            "",
            f"| Severity | File | Line | Description | Confidence |",
            f"|----------|------|------|-------------|------------|",
        ]
        severity_icons = {"bug": "🔴 Bug", "warning": "🟡 Warning", "suggestion": "🟢 Suggestion"}
        for issue in issues:
            sev = severity_icons.get(issue.get("severity", "suggestion"), "🔵")
            file_name = issue.get("file", "unknown")
            line_num = issue.get("line", 0)
            desc = issue.get("description", "").replace("|", "\\|")
            confidence = issue.get("confidence", 0)
            lines.append(f"| {sev} | `{file_name}` | {line_num} | {desc} | {confidence}% |")

        lines.append("")

    stats_parts = []
    if bugs:
        stats_parts.append(f"🔴 **{len(bugs)} bug{'s' if len(bugs) != 1 else ''}**")
    if warnings:
        stats_parts.append(f"🟡 **{len(warnings)} warning{'s' if len(warnings) != 1 else ''}**")
    if suggestions:
        stats_parts.append(f"🟢 **{len(suggestions)} suggestion{'s' if len(suggestions) != 1 else ''}**")

    if stats_parts:
        lines += ["### 📊 Summary Stats", "", " · ".join(stats_parts), ""]

    lines += [
        "---",
        f"*Generated by [PR Code Reviewer](https://github.com) — AI-powered code review*",
    ]

    return "\n".join(lines)


@router.post("/post-comment", response_model=CommentResponse)
async def post_comment(request: CommentRequest):
    """Post AI feedback as a comment on the GitHub PR."""
    try:
        owner, repo, pull_number = parse_pr_url(request.url)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

    comment_body = format_feedback_as_markdown(request.feedback, request.url)

    try:
        result = await post_pr_comment(
            owner=owner,
            repo=repo,
            pull_number=pull_number,
            body=comment_body,
            token=request.github_token,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"GitHub API error: {str(e)}")

    comment_url = result.get("html_url", request.url)

    return CommentResponse(
        success=True,
        comment_url=comment_url,
        message="Comment posted successfully!",
    )


class InlineCommentRequest(BaseModel):
    url: str
    file: str
    line: int
    body: str
    commit_id: str
    github_token: Optional[str] = None


@router.post("/post-inline-comment", response_model=CommentResponse)
async def post_inline_comment(request: InlineCommentRequest):
    """Post an inline review comment on a specific file/line in a PR."""
    try:
        owner, repo, pull_number = parse_pr_url(request.url)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

    # Format the comment body
    body = f"{request.body}\n\n---\n*Posted by [PR Code Reviewer](https://pr-reviewer-as.vercel.app/) — AI-powered code review*"

    try:
        result = await post_pr_review_comment(
            owner=owner,
            repo=repo,
            pull_number=pull_number,
            body=body,
            path=request.file,
            line=request.line,
            commit_id=request.commit_id,
            token=request.github_token,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"GitHub API error: {str(e)}")

    comment_url = result.get("html_url", request.url)

    return CommentResponse(
        success=True,
        comment_url=comment_url,
        message="Inline comment posted successfully!",
    )
